---
title: "Proyecto 1 R"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Carga de paquetes y de datos

```{r paquetes, warning=FALSE, message=FALSE}
# Paquete para manipulación de datos
library(dplyr)
# Paquete para manejo de datos vectoriales
library(sf)
# Paquetes para manejo de datos raster
library(terra)
# Paquete para manejo de tablas
library(DT)
# Paquetes para graficación
library(ggplot2)
library(plotly)
library(graphics)
# Paquete para mapas interactivos
library(leaflet)
```


```{r datos, warning=FALSE, message=FALSE}
# Lectura de una capa vectorial (GeoJSON) de división distrial de Santa Ana
limite_distrital <-
  st_read(
    "https://dvictoria2020.github.io/Proyecto1-R/limite_distrital.geojson",
    quiet = TRUE
  )

# Transformación del CRS del objeto división distrital
limite_distrital <-
  limite_distrital %>%
  st_transform(4326)

# Lectura de archivo CSV de patentes comerciales en Santa Ana
Patente_final <-
  st_read(
    "/vsicurl/https://dvictoria2020.github.io/Proyecto1-R/Patente_final.csv",
    options = c(
      "X_POSSIBLE_NAMES=Latitud",
      "Y_POSSIBLE_NAMES=Longitud"
    ),
    quiet = TRUE
  )

# Asignación de un CRS al objeto patentes
st_crs(Patente_final) <- 4326


# Lectura de capa raster de uso urbano
uso_urbano_rWGS <-
  rast(
    "/vsicurl/https://dvictoria2020.github.io/Proyecto1-R/uso_urbano_rWGS.tif",
  )
```


# Tabla

```{r tabla}
 Patente_final %>%
  st_drop_geometry() %>%
  select(N_patente, Aprobacion, Actividad, Nombre_comercio, Permiso_salud, Rotulo, N_finca, Tipo_persona, Direccion_, Distrito) %>%
  datatable(Patente_final, options = list(
    language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json'),
    pageLenth =5
  ))
```




# Gráfico barras apiladas

```{r grafico-1}
tipo_persona_distrito <-
  Patente_final %>%
  dplyr::count(Tipo_persona, Distrito)
```

```{r grafico-barras-apiladas}
  ggplot() + geom_col(
      data= tipo_persona_distrito,
      aes(x= Distrito,
          y= n, fill = Tipo_persona), width = 0.7)+
  
      ggtitle( "Distribución de patentes comerciales por tipo de personería
                          en los distritos de Santa Ana") +
      xlab("Distrito") + 
      ylab("Total de patentes") +
      scale_fill_manual(values = c("#FFE4C4", "#8B7D6B")) +
      theme (
        legend.title = element_blank(),
        legend.position = "right",
        plot.title = element_text(size = 14, face = "plain")
        
  )

```


```{r grafico-2-pastel-licencias-por-distrito}

# Convertimos a porcentaje
  
porcentaje <- Patente_final %>%
  group_by(Distrito) %>%
  count() %>%
  ungroup() %>%
  mutate(percentage = `n` / sum(`n`) * 100)


ggplot(porcentaje, aes(x = 1, y = percentage, fill = Distrito)) +
  geom_bar(stat = "identity", colour = "black", size = 0.25) +
  geom_text(aes(label = paste0(round(percentage, 1), "%")),
            position = position_stack(vjust = 0.5)) +
  coord_polar(theta = "y") +
  labs(title = "Porcentaje de licencias comerciales y de licor según 
                 distrito en el cantón Santa Ana") +
  theme_void() + scale_fill_brewer(palette = "Dark2")


```


```{r grafico-3-pastel-licencias-por-distrito}

# Convertimos a porcentaje
  
porcentaje_rotulo <- Patente_final %>%
  group_by(Rotulo) %>%
  count() %>%
  ungroup() %>%
  mutate(percentage = `n` / sum(`n`) * 100)


ggplot(porcentaje_rotulo, aes(x = 1, y = percentage, fill = Rotulo)) +
  geom_bar(stat = "identity", colour = "black", size = 0.25) +
  geom_text(aes(label = paste0(round(percentage, 1), "%")),
            position = position_stack(vjust = 0.5)) +
  coord_polar(theta = "y") +
  labs(title = "Locales comerciales que han tramitado una 
  solicitud de rótulo en el cantón Santa Ana") +
  theme_void() + scale_fill_brewer(palette = "Blues")

```



### Mapa de distribución


```{r mapa, warning=FALSE}
# Conversión del objeto uso a la clase RasterLayer
uso_urbano_rWGS_rl <- raster::raster(uso_urbano_rWGS)

# Mapa leaflet
leaflet() %>%
  
  addTiles(options = providerTileOptions(noWrap = TRUE), group="Open Street Maps") %>%
  addProviderTiles("Esri.WorldImagery", group="Imagen Satelital")%>%
  
  addRasterImage(
    uso_urbano_rWGS_rl,
    color= "#DDB892",
    opacity = 0.6,
    group = "Uso Urbano 2005"
  )%>%
  
  addPolygons(
    data = limite_distrital,
    color = "purple",
    fillColor = "transparent",
    stroke = TRUE,
    weight = 2.0,
    group = "Limite distrital"
  )%>% 
  
  addCircleMarkers(
    data = Patente_final,
    stroke = F,
    radius = 4,
    fillColor = 'orange',
    fillOpacity = 1,
    clusterOptions = markerClusterOptions(),
    group = "Patentes comerciales"
  )%>% 
  
  addMiniMap(
    tiles = providers$OpenStreetMap,
    toggleDisplay = TRUE
  )%>%
 
 addLayersControl(
   baseGroups = c("Open Street Maps","Imagen Satelital"),
   overlayGroups = c("Uso Urbano 2005","Limite distrital", "Patentes comerciales"), 
   options = layersControlOptions(collapsed = FALSE)
  )
	    
```
